--
-- PostgreSQL database dump
--

-- Dumped from database version 14.5
-- Dumped by pg_dump version 14.5

-- Started on 2023-03-31 13:43:24

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 209 (class 1259 OID 33095)
-- Name: book; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.book (
    id integer NOT NULL,
    human_id integer,
    name character varying,
    author character varying,
    year_of_publication integer,
    taken_at timestamp without time zone
);


ALTER TABLE public.book OWNER TO postgres;

--
-- TOC entry 210 (class 1259 OID 33100)
-- Name: book_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.book ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.book_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 211 (class 1259 OID 33101)
-- Name: human; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.human (
    id integer NOT NULL,
    full_name character varying,
    year_of_birth integer
);


ALTER TABLE public.human OWNER TO postgres;

--
-- TOC entry 212 (class 1259 OID 33106)
-- Name: people_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.human ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.people_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3315 (class 0 OID 33095)
-- Dependencies: 209
-- Data for Name: book; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.book (id, human_id, name, author, year_of_publication, taken_at) VALUES (5, NULL, 'Метро 2034', 'Дмитрий Глуховский', 2009, NULL);
INSERT INTO public.book (id, human_id, name, author, year_of_publication, taken_at) VALUES (7, NULL, 'Преступление и наказание', 'Федор Достоевский', 1866, NULL);
INSERT INTO public.book (id, human_id, name, author, year_of_publication, taken_at) VALUES (3, 7, 'Философия Java', 'Брюс Эккель', 2019, '2023-03-20 10:12:00');
INSERT INTO public.book (id, human_id, name, author, year_of_publication, taken_at) VALUES (10, NULL, 'Палата № 5', 'Геннадий Выдуманный', 1980, NULL);
INSERT INTO public.book (id, human_id, name, author, year_of_publication, taken_at) VALUES (4, 7, 'Война и мир', 'Лев Николаевич Толстой', 1959, '2023-03-31 11:10:11.307');
INSERT INTO public.book (id, human_id, name, author, year_of_publication, taken_at) VALUES (8, 10, 'Палата № 6', 'Антон Чехов', 1892, '2023-03-31 11:10:20.049');


--
-- TOC entry 3317 (class 0 OID 33101)
-- Dependencies: 211
-- Data for Name: human; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.human (id, full_name, year_of_birth) VALUES (3, 'Вешников Александр Борисович', 1983);
INSERT INTO public.human (id, full_name, year_of_birth) VALUES (10, 'Хвалина Нина Сергеевна', 1901);
INSERT INTO public.human (id, full_name, year_of_birth) VALUES (7, 'Таран Григорий Валерьевич', 1996);
INSERT INTO public.human (id, full_name, year_of_birth) VALUES (11, 'Аксенов Валерий Вячеславович', 1950);


--
-- TOC entry 3324 (class 0 OID 0)
-- Dependencies: 210
-- Name: book_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.book_id_seq', 12, true);


--
-- TOC entry 3325 (class 0 OID 0)
-- Dependencies: 212
-- Name: people_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.people_id_seq', 11, true);


--
-- TOC entry 3170 (class 2606 OID 33108)
-- Name: book book_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.book
    ADD CONSTRAINT book_pkey PRIMARY KEY (id);


--
-- TOC entry 3172 (class 2606 OID 33110)
-- Name: human people_fio_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.human
    ADD CONSTRAINT people_fio_key UNIQUE (full_name);


--
-- TOC entry 3174 (class 2606 OID 33112)
-- Name: human people_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.human
    ADD CONSTRAINT people_pkey PRIMARY KEY (id);


--
-- TOC entry 3175 (class 2606 OID 33113)
-- Name: book book_human_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.book
    ADD CONSTRAINT book_human_id_fkey FOREIGN KEY (human_id) REFERENCES public.human(id) ON DELETE SET NULL;


-- Completed on 2023-03-31 13:43:28

--
-- PostgreSQL database dump complete
--

